/* Auto-generated by build-mui-themes.ts — do not edit by hand */
import { createTheme, ThemeOptions } from '@mui/material/styles';

export const themeOptions: ThemeOptions = {
  "palette": {
    "mode": "light",
    "primary": {
      "main": "rgba(50,98,141,1)",
      "contrastText": "rgba(235,239,244,1)"
    },
    "secondary": {
      "main": "rgba(65,94,91,1)"
    },
    "background": {
      "default": "rgba(158,158,158,1)",
      "paper": "rgba(189,189,189,1)"
    },
    "text": {
      "primary": "rgba(0,0,0,0.8700000047683716)",
      "secondary": "rgba(0,0,0,0.699999988079071)",
      "disabled": "rgba(0,0,0,0.3799999952316284)"
    },
    "divider": "rgba(0,0,0,0.11999999731779099)",
    "action": {
      "hover": "rgba(0,0,0,0.05999999865889549)",
      "selected": "rgba(0,0,0,0.11999999731779099)",
      "disabled": "rgba(0,0,0,0.3799999952316284)",
      "disabledBackground": "rgba(0,0,0,0.11999999731779099)"
    }
  },
  "shape": {
    "borderRadius": 8
  },
  "components": {
    "MuiButton": {
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "&:focus-visible": {
            "outline": "2px solid rgba(50,98,141,0.30000001192092896)",
            "outlineOffset": 2
          }
        },
        "containedPrimary": {
          "backgroundColor": "rgba(50,98,141,1)",
          "color": "rgba(235,239,244,1)",
          "&:hover": {
            "backgroundColor": "rgba(42,82,118,1)",
            "boxShadow": "none"
          },
          "&:active": {
            "backgroundColor": "rgba(42,82,118,1)"
          },
          "&.Mui-disabled": {
            "color": "rgba(0,0,0,0.3799999952316284)",
            "backgroundColor": "rgba(0,0,0,0.11999999731779099)"
          }
        },
        "outlinedPrimary": {
          "borderColor": "rgba(50,98,141,1)",
          "color": "rgba(50,98,141,1)",
          "&:hover": {
            "backgroundColor": "rgba(50,98,141,0.05999999865889549)"
          }
        },
        "textPrimary": {
          "color": "rgba(50,98,141,1)",
          "&:hover": {
            "backgroundColor": "rgba(50,98,141,0.05999999865889549)"
          }
        }
      }
    },
    "MuiCard": {
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "backgroundColor": "rgba(189,189,189,1)",
          "border": "1px solid rgba(0,0,0,0.11999999731779099)"
        }
      }
    },
    "MuiChip": {
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "border": "1px solid rgba(0,0,0,0.11999999731779099)",
          "backgroundColor": "rgba(189,189,189,1)",
          "&.MuiChip-colorPrimary": {
            "backgroundColor": "rgba(50,98,141,0.1599999964237213)",
            "color": "rgba(42,82,118,1)"
          }
        }
      }
    }
  }
};
const theme = createTheme(themeOptions);
export default theme;
