/* Auto-generated by build-mui-themes.ts — do not edit by hand */
import { createTheme, ThemeOptions } from '@mui/material/styles';

export const themeOptions: ThemeOptions = {
  "palette": {
    "mode": "light",
    "primary": {
      "main": "rgba(50,98,141,1)",
      "contrastText": "rgba(235,239,244,1)"
    },
    "secondary": {
      "main": "rgba(65,94,91,1)"
    },
    "background": {
      "default": "rgba(158,158,158,1)",
      "paper": "rgba(189,189,189,1)"
    },
    "text": {
      "primary": "rgba(0,0,0,0.8700000047683716)",
      "secondary": "rgba(0,0,0,0.699999988079071)",
      "disabled": "rgba(0,0,0,0.3799999952316284)"
    },
    "divider": "rgba(0,0,0,0.11999999731779099)",
    "action": {
      "hover": "rgba(0,0,0,0.05999999865889549)",
      "selected": "rgba(0,0,0,0.11999999731779099)",
      "disabled": "rgba(0,0,0,0.3799999952316284)",
      "disabledBackground": "rgba(0,0,0,0.11999999731779099)"
    }
  },
  "shape": {
    "borderRadius": 8
  },
  "components": {
    "MuiButton": {
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "&:focus-visible": {
            "outline": "2px solid rgba(50,98,141,0.30000001192092896)",
            "outlineOffset": 2
          }
        },
        "containedPrimary": {
          "backgroundColor": "rgba(50,98,141,1)",
          "color": "rgba(235,239,244,1)",
          "&:hover": {
            "backgroundColor": "rgba(42,82,118,1)",
            "boxShadow": "none"
          },
          "&:active": {
            "backgroundColor": "rgba(42,82,118,1)"
          },
          "&.Mui-disabled": {
            "color": "rgba(0,0,0,0.3799999952316284)",
            "backgroundColor": "rgba(0,0,0,0.11999999731779099)"
          }
        },
        "outlinedPrimary": {
          "borderColor": "rgba(50,98,141,1)",
          "color": "rgba(50,98,141,1)",
          "&:hover": {
            "backgroundColor": "rgba(50,98,141,0.05999999865889549)"
          }
        },
        "textPrimary": {
          "color": "rgba(50,98,141,1)",
          "&:hover": {
            "backgroundColor": "rgba(50,98,141,0.05999999865889549)"
          }
        }
      }
    },
    "MuiCard": {
      "defaultProps": {
        "elevation": 0
      },
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "border": "1px solid rgba(0,0,0,0.11999999731779099)"
        }
      },
      "variants": [
        {
          "props": {
            "elevation": 0
          },
          "style": {
            "backgroundColor": "rgba(158,158,158,1)",
            "--mui-palette-background-paper": "rgba(158,158,158,1)"
          }
        },
        {
          "props": {
            "elevation": 1
          },
          "style": {
            "backgroundColor": "rgba(189,189,189,1)",
            "--mui-palette-background-paper": "rgba(189,189,189,1)"
          }
        },
        {
          "props": {
            "elevation": 2
          },
          "style": {
            "backgroundColor": "rgba(210,210,210,1)",
            "--mui-palette-background-paper": "rgba(210,210,210,1)"
          }
        },
        {
          "props": {
            "elevation": 3
          },
          "style": {
            "backgroundColor": "rgba(224,224,224,1)",
            "--mui-palette-background-paper": "rgba(224,224,224,1)"
          }
        },
        {
          "props": {
            "elevation": 4
          },
          "style": {
            "backgroundColor": "rgba(238,238,238,1)",
            "--mui-palette-background-paper": "rgba(238,238,238,1)"
          }
        },
        {
          "props": {
            "elevation": 5
          },
          "style": {
            "backgroundColor": "rgba(245,245,245,1)",
            "--mui-palette-background-paper": "rgba(245,245,245,1)"
          }
        },
        {
          "props": {
            "elevation": 6
          },
          "style": {
            "backgroundColor": "rgba(255,255,255,1)",
            "--mui-palette-background-paper": "rgba(255,255,255,1)"
          }
        }
      ]
    },
    "MuiChip": {
      "styleOverrides": {
        "root": {
          "borderRadius": 100,
          "border": "1px solid rgba(0,0,0,0.11999999731779099)",
          "backgroundColor": "rgba(255,255,255,1)",
          "color": "rgba(0,0,0,0.699999988079071)"
        },
        "filled": {},
        "outlined": {},
        "colorPrimary": {},
        "colorSecondary": {},
        "colorError": {},
        "colorWarning": {},
        "colorInfo": {},
        "colorSuccess": {}
      },
      "variants": [
        {
          "props": {
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "rgba(255,255,255,1)",
            "color": "rgba(0,0,0,0.699999988079071)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(0,0,0,0.699999988079071)"
            }
          }
        },
        {
          "props": {
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "rgba(0,0,0,0.11999999731779099)",
            "color": "rgba(0,0,0,0.699999988079071)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(0,0,0,0.699999988079071)"
            }
          }
        },
        {
          "props": {
            "color": "primary",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "rgba(50,98,141,1)",
            "color": "rgba(235,239,244,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(235,239,244,1)"
            }
          }
        },
        {
          "props": {
            "color": "primary",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "rgba(50,98,141,1)",
            "color": "rgba(50,98,141,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(50,98,141,1)"
            }
          }
        },
        {
          "props": {
            "color": "secondary",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "rgba(65,94,91,1)",
            "color": "rgba(235,239,244,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(235,239,244,1)"
            }
          }
        },
        {
          "props": {
            "color": "secondary",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "rgba(65,94,91,1)",
            "color": "rgba(65,94,91,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(65,94,91,1)"
            }
          }
        },
        {
          "props": {
            "color": "error",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "rgba(183,51,42,1)",
            "color": "rgba(251,236,235,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(251,236,235,1)"
            }
          }
        },
        {
          "props": {
            "color": "error",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "rgba(183,51,42,1)",
            "color": "rgba(183,51,42,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(183,51,42,1)"
            }
          }
        },
        {
          "props": {
            "color": "warning",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "rgba(255,189,48,1)",
            "color": "rgba(77,52,0,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(77,52,0,1)"
            }
          }
        },
        {
          "props": {
            "color": "warning",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "rgba(255,189,48,1)",
            "color": "rgba(255,189,48,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(255,189,48,1)"
            }
          }
        },
        {
          "props": {
            "color": "info",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "rgba(2,123,184,1)",
            "color": "rgba(230,244,252,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(230,244,252,1)"
            }
          }
        },
        {
          "props": {
            "color": "info",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "rgba(2,123,184,1)",
            "color": "rgba(2,123,184,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(2,123,184,1)"
            }
          }
        },
        {
          "props": {
            "color": "success",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "rgba(24,98,24,1)",
            "color": "rgba(255,255,255,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(255,255,255,1)"
            }
          }
        },
        {
          "props": {
            "color": "success",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "rgba(24,98,24,1)",
            "color": "rgba(24,98,24,1)",
            "& .MuiChip-deleteIcon": {
              "color": "rgba(24,98,24,1)"
            }
          }
        }
      ]
    },
    "MuiFormControl": {
      "styleOverrides": {
        "root": {
          "backgroundColor": "transparent"
        }
      }
    },
    "MuiFormHelperText": {
      "styleOverrides": {
        "root": {
          "color": "rgba(0,0,0,0.699999988079071)",
          "backgroundColor": "transparent"
        }
      }
    },
    "MuiFormLabel": {
      "styleOverrides": {
        "root": {
          "color": "rgba(0,0,0,0.699999988079071)",
          "fontWeight": 500,
          "fontSize": "1rem"
        },
        "asterisk": {
          "color": "rgba(50,98,141,1)"
        }
      }
    },
    "MuiMenu": {
      "styleOverrides": {
        "paper": {
          "borderRadius": 8,
          "backgroundColor": "rgba(255,255,255,1)",
          "boxShadow": "rgba(210,210,210,1)",
          "minWidth": 160,
          "padding": "4px 0"
        },
        "list": {
          "paddingTop": 8,
          "paddingBottom": 8,
          "paddingLeft": 16,
          "paddingRight": 16
        }
      }
    },
    "MuiMenuItem": {
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "textTransform": "none",
          "color": "rgba(0,0,0,0.8700000047683716)",
          "backgroundColor": "rgba(255,255,255,1)",
          "&:hover": {
            "backgroundColor": "rgba(0,0,0,0.05999999865889549)"
          },
          "&.Mui-selected": {
            "backgroundColor": "rgba(50,98,141,1)",
            "color": "rgba(235,239,244,1)",
            "&:hover": {
              "backgroundColor": "rgba(42,82,118,1)"
            }
          },
          "&.Mui-disabled": {
            "color": "rgba(0,0,0,0.3799999952316284)",
            "backgroundColor": "rgba(0,0,0,0.11999999731779099)"
          },
          "&:focus-visible": {
            "outline": "2px solid rgba(50,98,141,0.30000001192092896)",
            "outlineOffset": 2
          }
        }
      }
    },
    "MuiPaper": {
      "defaultProps": {
        "elevation": 0
      },
      "styleOverrides": {
        "root": {
          "borderRadius": 8
        },
        "outlined": {
          "border": "1px solid rgba(0,0,0,0.11999999731779099)",
          "backgroundColor": "rgba(158,158,158,1)"
        }
      },
      "variants": [
        {
          "props": {
            "elevation": 0
          },
          "style": {
            "backgroundColor": "rgba(158,158,158,1)",
            "--mui-palette-background-paper": "rgba(158,158,158,1)"
          }
        },
        {
          "props": {
            "elevation": 1
          },
          "style": {
            "backgroundColor": "rgba(189,189,189,1)",
            "--mui-palette-background-paper": "rgba(189,189,189,1)"
          }
        },
        {
          "props": {
            "elevation": 2
          },
          "style": {
            "backgroundColor": "rgba(210,210,210,1)",
            "--mui-palette-background-paper": "rgba(210,210,210,1)"
          }
        },
        {
          "props": {
            "elevation": 3
          },
          "style": {
            "backgroundColor": "rgba(224,224,224,1)",
            "--mui-palette-background-paper": "rgba(224,224,224,1)"
          }
        },
        {
          "props": {
            "elevation": 4
          },
          "style": {
            "backgroundColor": "rgba(238,238,238,1)",
            "--mui-palette-background-paper": "rgba(238,238,238,1)"
          }
        },
        {
          "props": {
            "elevation": 5
          },
          "style": {
            "backgroundColor": "rgba(245,245,245,1)",
            "--mui-palette-background-paper": "rgba(245,245,245,1)"
          }
        },
        {
          "props": {
            "elevation": 6
          },
          "style": {
            "backgroundColor": "rgba(255,255,255,1)",
            "--mui-palette-background-paper": "rgba(255,255,255,1)"
          }
        }
      ]
    },
    "MuiSelect": {
      "styleOverrides": {
        "select": {
          "&:focus": {
            "backgroundColor": "transparent"
          },
          "color": "rgba(0,0,0,0.8700000047683716)",
          "backgroundColor": "rgba(255,255,255,1)",
          "&.Mui-disabled": {
            "color": "rgba(0,0,0,0.3799999952316284)",
            "backgroundColor": "rgba(0,0,0,0.11999999731779099)"
          }
        },
        "icon": {
          "color": "rgba(0,0,0,0.699999988079071)"
        }
      }
    },
    "MuiSwitch": {
      "styleOverrides": {
        "switchBase": {
          "&.MuiSwitch-colorPrimary.Mui-checked": {
            "color": "rgba(50,98,141,1)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "rgba(50, 98, 141, 0.5)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "rgba(50,98,141,1)"
            }
          },
          "&.MuiSwitch-colorSecondary.Mui-checked": {
            "color": "rgba(65,94,91,1)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "rgba(65, 94, 91, 0.5)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "rgba(65,94,91,1)"
            }
          },
          "&.MuiSwitch-colorError.Mui-checked": {
            "color": "rgba(183,51,42,1)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "rgba(183, 51, 42, 0.5)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "rgba(183,51,42,1)"
            }
          },
          "&.MuiSwitch-colorWarning.Mui-checked": {
            "color": "rgba(255,189,48,1)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "rgba(255, 189, 48, 0.5)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "rgba(255,189,48,1)"
            }
          },
          "&.MuiSwitch-colorInfo.Mui-checked": {
            "color": "rgba(2,123,184,1)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "rgba(2, 123, 184, 0.5)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "rgba(2,123,184,1)"
            }
          },
          "&.MuiSwitch-colorSuccess.Mui-checked": {
            "color": "rgba(24,98,24,1)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "rgba(24, 98, 24, 0.5)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "rgba(24,98,24,1)"
            }
          },
          "&.Mui-disabled": {
            "color": "rgba(0,0,0,0.3799999952316284)"
          },
          "&.Mui-checked.Mui-disabled": {
            "color": "rgba(0,0,0,0.3799999952316284)",
            "& + .MuiSwitch-track": {
              "opacity": 0.5
            }
          }
        },
        "thumb": {
          "backgroundColor": "#fff"
        },
        "track": {
          "backgroundColor": "rgba(0,0,0,0.11999999731779099)"
        }
      }
    },
    "MuiTab": {
      "styleOverrides": {
        "root": {
          "color": "rgba(0,0,0,0.699999988079071)",
          "&.Mui-selected": {
            "color": "rgba(50,98,141,1)"
          },
          "&:hover": {
            "backgroundColor": "rgba(0,0,0,0.05999999865889549)"
          },
          "&:focus-visible": {
            "outline": "2px solid rgba(50,98,141,0.30000001192092896)",
            "outlineOffset": 2,
            "borderRadius": 0
          }
        }
      }
    },
    "MuiTabs": {
      "styleOverrides": {
        "root": {
          "backgroundColor": "transparent",
          "minHeight": 48,
          "borderBottom": "1px solid rgba(0,0,0,0.11999999731779099)"
        },
        "indicator": {
          "height": 3,
          "borderRadius": 2,
          "backgroundColor": "rgba(50,98,141,1)"
        },
        "scrollButtons": {
          "color": "rgba(0,0,0,0.699999988079071)",
          "&.Mui-disabled": {
            "opacity": 0.3
          }
        },
        "flexContainer": {
          "minHeight": 48
        }
      }
    },
    "MuiTextField": {
      "defaultProps": {
        "variant": "outlined"
      },
      "styleOverrides": {
        "root": {
          "borderRadius": 8
        }
      }
    },
    "MuiOutlinedInput": {
      "styleOverrides": {
        "root": {
          "backgroundColor": "#fff",
          "&.Mui-disabled": {
            "backgroundColor": "rgba(0,0,0,0.11999999731779099)"
          }
        }
      }
    }
  }
};
const theme = createTheme(themeOptions);
export default theme;
