/* Auto-generated by build-mui-themes.ts — do not edit by hand */
import { createTheme, ThemeOptions } from '@mui/material/styles';

export const themeOptions: ThemeOptions = {
  "palette": {
    "mode": "light",
    "primary": {
      "main": "rgba(50,98,141,1)",
      "contrastText": "rgba(235,239,244,1)"
    },
    "secondary": {
      "main": "rgba(65,94,91,1)",
      "contrastText": "rgba(255,255,255,1)"
    },
    "background": {
      "default": "rgba(158,158,158,1)",
      "paper": "rgba(189,189,189,1)"
    },
    "text": {
      "primary": "rgba(0,0,0,0.8700000047683716)",
      "secondary": "rgba(0,0,0,0.699999988079071)",
      "disabled": "rgba(0,0,0,0.3799999952316284)"
    },
    "divider": "rgba(0,0,0,0.11999999731779099)",
    "action": {
      "hover": "rgba(0,0,0,0.05999999865889549)",
      "selected": "rgba(0,0,0,0.11999999731779099)",
      "disabled": "rgba(0,0,0,0.3799999952316284)",
      "disabledBackground": "rgba(0,0,0,0.11999999731779099)"
    }
  },
  "shape": {
    "borderRadius": 8
  },
  "components": {
    "MuiAlert": {
      "styleOverrides": {
        "root": {
          "borderRadius": 8
        },
        "standardSuccess": {
          "backgroundColor": "var(--theme-base-feedback-success-light, #e8f5e9)",
          "color": "var(--theme-base-feedback-success-dark, #1b5e20)"
        },
        "standardInfo": {
          "backgroundColor": "var(--theme-base-feedback-info-light, #e3f2fd)",
          "color": "var(--theme-base-feedback-info-dark, #01579b)"
        },
        "standardWarning": {
          "backgroundColor": "var(--theme-base-feedback-warning-light, #fff4e5)",
          "color": "var(--theme-base-feedback-warning-dark, #b53d00)"
        },
        "standardError": {
          "backgroundColor": "var(--theme-base-feedback-error-light, #fde7e9)",
          "color": "var(--theme-base-feedback-error-dark, #9a0007)"
        },
        "filledSuccess": {
          "backgroundColor": "var(--theme-base-feedback-success-main, #2e7d32)",
          "color": "var(--theme-base-feedback-success-contrast-text, #ffffff)"
        },
        "filledInfo": {
          "backgroundColor": "var(--theme-base-feedback-info-main, #0288d1)",
          "color": "var(--theme-base-feedback-info-contrast-text, #ffffff)"
        },
        "filledWarning": {
          "backgroundColor": "var(--theme-base-feedback-warning-main, #ed6c02)",
          "color": "var(--theme-base-feedback-warning-contrast-text, #1a1300)"
        },
        "filledError": {
          "backgroundColor": "var(--theme-base-feedback-error-main, #d32f2f)",
          "color": "var(--theme-base-feedback-error-contrast-text, #ffffff)"
        },
        "outlinedSuccess": {
          "color": "var(--theme-base-feedback-success-dark, #1b5e20)",
          "border": "1px solid",
          "borderColor": "var(--theme-base-feedback-success-main, #2e7d32)"
        },
        "outlinedInfo": {
          "color": "var(--theme-base-feedback-info-dark, #01579b)",
          "border": "1px solid",
          "borderColor": "var(--theme-base-feedback-info-main, #0288d1)"
        },
        "outlinedWarning": {
          "color": "var(--theme-base-feedback-warning-dark, #b53d00)",
          "border": "1px solid",
          "borderColor": "var(--theme-base-feedback-warning-main, #ed6c02)"
        },
        "outlinedError": {
          "color": "var(--theme-base-feedback-error-dark, #9a0007)",
          "border": "1px solid",
          "borderColor": "var(--theme-base-feedback-error-main, #d32f2f)"
        }
      }
    },
    "MuiButton": {
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "textTransform": "none",
          "boxShadow": "none",
          "&:focus-visible": {
            "outline": "2px solid var(--theme-base-primary-states-focus-visible, rgba(50,98,141,0.30))",
            "outlineOffset": 2
          },
          "&.MuiButton-containedPrimary": {
            "backgroundColor": "var(--theme-base-primary-main, rgba(50,98,141,1))",
            "color": "var(--theme-base-primary-on-main, rgba(235,239,244,1))",
            "&:hover": {
              "backgroundColor": "var(--theme-base-primary-dark, rgba(42,82,118,1))",
              "boxShadow": "none"
            },
            "&:active": {
              "backgroundColor": "var(--theme-base-primary-dark, rgba(42,82,118,1))",
              "boxShadow": "none"
            }
          },
          "&.MuiButton-outlinedPrimary": {
            "color": "var(--theme-base-primary-main, rgba(50,98,141,1))",
            "borderColor": "var(--theme-base-primary-states-outlined-border, rgba(50,98,141,0.50))",
            "&:hover": {
              "backgroundColor": "var(--theme-base-primary-states-hover, rgba(50,98,141,0.06))"
            }
          },
          "&.MuiButton-textPrimary": {
            "color": "var(--theme-base-primary-main, rgba(50,98,141,1))",
            "&:hover": {
              "backgroundColor": "var(--theme-base-primary-states-hover, rgba(50,98,141,0.06))"
            }
          },
          "&.MuiButton-containedSecondary": {
            "backgroundColor": "var(--theme-base-secondary-main, rgba(65,94,91,1))",
            "color": "var(--theme-base-secondary-on-main, rgba(255,255,255,1))",
            "&:hover": {
              "backgroundColor": "var(--theme-base-secondary-dark, rgba(113,164,158,1))",
              "boxShadow": "none"
            },
            "&:active": {
              "backgroundColor": "var(--theme-base-secondary-dark, rgba(113,164,158,1))",
              "boxShadow": "none"
            }
          },
          "&.MuiButton-outlinedSecondary": {
            "color": "var(--theme-base-secondary-main, rgba(65,94,91,1))",
            "borderColor": "var(--theme-base-secondary-states-outlined-border, rgba(65,94,91,0.50))",
            "&:hover": {
              "backgroundColor": "var(--theme-base-secondary-states-hover, rgba(65,94,91,0.06))"
            }
          },
          "&.MuiButton-textSecondary": {
            "color": "var(--theme-base-secondary-main, rgba(65,94,91,1))",
            "&:hover": {
              "backgroundColor": "var(--theme-base-secondary-states-hover, rgba(65,94,91,0.06))"
            }
          }
        },
        "containedPrimary": {
          "backgroundColor": "var(--theme-base-primary-main, rgba(50,98,141,1))",
          "color": "var(--theme-base-primary-on-main, rgba(235,239,244,1))",
          "boxShadow": "none",
          "&:hover": {
            "backgroundColor": "var(--theme-base-primary-dark, rgba(42,82,118,1))",
            "boxShadow": "none"
          },
          "&:active": {
            "backgroundColor": "var(--theme-base-primary-dark, rgba(42,82,118,1))",
            "boxShadow": "none"
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))",
            "backgroundColor": "var(--theme-base-action-disabled-background, rgba(0,0,0,0.12))",
            "boxShadow": "none"
          }
        },
        "outlinedPrimary": {
          "color": "var(--theme-base-primary-main, rgba(50,98,141,1))",
          "borderColor": "var(--theme-base-primary-states-outlined-border, rgba(50,98,141,0.50))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-primary-states-hover, rgba(50,98,141,0.06))"
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))",
            "borderColor": "var(--theme-base-action-disabled-background, rgba(0,0,0,0.12))"
          }
        },
        "textPrimary": {
          "color": "var(--theme-base-primary-main, rgba(50,98,141,1))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-primary-states-hover, rgba(50,98,141,0.06))"
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))"
          }
        },
        "containedSecondary": {
          "backgroundColor": "var(--theme-base-secondary-main, rgba(65,94,91,1))",
          "color": "var(--theme-base-secondary-on-main, rgba(255,255,255,1))",
          "boxShadow": "none",
          "&:hover": {
            "backgroundColor": "var(--theme-base-secondary-dark, rgba(113,164,158,1))",
            "boxShadow": "none"
          },
          "&:active": {
            "backgroundColor": "var(--theme-base-secondary-dark, rgba(113,164,158,1))",
            "boxShadow": "none"
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))",
            "backgroundColor": "var(--theme-base-action-disabled-background, rgba(0,0,0,0.12))",
            "boxShadow": "none"
          }
        },
        "outlinedSecondary": {
          "color": "var(--theme-base-secondary-main, rgba(65,94,91,1))",
          "borderColor": "var(--theme-base-secondary-states-outlined-border, rgba(65,94,91,0.50))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-secondary-states-hover, rgba(65,94,91,0.06))"
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))",
            "borderColor": "var(--theme-base-action-disabled-background, rgba(0,0,0,0.12))"
          }
        },
        "textSecondary": {
          "color": "var(--theme-base-secondary-main, rgba(65,94,91,1))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-secondary-states-hover, rgba(65,94,91,0.06))"
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))"
          }
        },
        "containedError": {
          "backgroundColor": "var(--theme-base-feedback-error-main, rgba(211,47,47,1))",
          "color": "var(--theme-base-feedback-error-contrast-text, rgba(255,255,255,1))",
          "boxShadow": "none",
          "&:hover": {
            "backgroundColor": "var(--theme-base-feedback-error-dark, rgba(154,0,7,1))",
            "boxShadow": "none"
          },
          "&:active": {
            "backgroundColor": "var(--theme-base-feedback-error-dark, rgba(154,0,7,1))",
            "boxShadow": "none"
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))",
            "backgroundColor": "var(--theme-base-action-disabled-background, rgba(0,0,0,0.12))",
            "boxShadow": "none"
          }
        },
        "outlinedError": {
          "color": "var(--theme-base-feedback-error-main, rgba(211,47,47,1))",
          "borderColor": "var(--theme-base-feedback-error-main, rgba(211,47,47,1))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-primary-states-hover, rgba(50,98,141,0.06))"
          }
        },
        "textError": {
          "color": "var(--theme-base-feedback-error-main, rgba(211,47,47,1))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-primary-states-hover, rgba(50,98,141,0.06))"
          }
        },
        "containedWarning": {
          "backgroundColor": "var(--theme-base-feedback-warning-main, rgba(237,108,2,1))",
          "color": "var(--theme-base-feedback-warning-contrast-text, rgba(26,19,0,1))",
          "boxShadow": "none",
          "&:hover": {
            "backgroundColor": "var(--theme-base-feedback-warning-dark, rgba(181,61,0,1))",
            "boxShadow": "none"
          },
          "&:active": {
            "backgroundColor": "var(--theme-base-feedback-warning-dark, rgba(181,61,0,1))",
            "boxShadow": "none"
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))",
            "backgroundColor": "var(--theme-base-action-disabled-background, rgba(0,0,0,0.12))",
            "boxShadow": "none"
          }
        },
        "outlinedWarning": {
          "color": "var(--theme-base-feedback-warning-main, rgba(237,108,2,1))",
          "borderColor": "var(--theme-base-feedback-warning-main, rgba(237,108,2,1))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-secondary-states-hover, rgba(65,94,91,0.06))"
          }
        },
        "textWarning": {
          "color": "var(--theme-base-feedback-warning-main, rgba(237,108,2,1))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-secondary-states-hover, rgba(65,94,91,0.06))"
          }
        },
        "containedInfo": {
          "backgroundColor": "var(--theme-base-feedback-info-main, rgba(2,136,209,1))",
          "color": "var(--theme-base-feedback-info-contrast-text, rgba(255,255,255,1))",
          "boxShadow": "none",
          "&:hover": {
            "backgroundColor": "var(--theme-base-feedback-info-dark, rgba(1,87,155,1))",
            "boxShadow": "none"
          },
          "&:active": {
            "backgroundColor": "var(--theme-base-feedback-info-dark, rgba(1,87,155,1))",
            "boxShadow": "none"
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))",
            "backgroundColor": "var(--theme-base-action-disabled-background, rgba(0,0,0,0.12))",
            "boxShadow": "none"
          }
        },
        "outlinedInfo": {
          "color": "var(--theme-base-feedback-info-main, rgba(2,136,209,1))",
          "borderColor": "var(--theme-base-feedback-info-main, rgba(2,136,209,1))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-primary-states-hover, rgba(50,98,141,0.06))"
          }
        },
        "textInfo": {
          "color": "var(--theme-base-feedback-info-main, rgba(2,136,209,1))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-primary-states-hover, rgba(50,98,141,0.06))"
          }
        },
        "containedSuccess": {
          "backgroundColor": "var(--theme-base-feedback-success-main, rgba(46,125,50,1))",
          "color": "var(--theme-base-feedback-success-contrast-text, rgba(255,255,255,1))",
          "boxShadow": "none",
          "&:hover": {
            "backgroundColor": "var(--theme-base-feedback-success-dark, rgba(27,94,32,1))",
            "boxShadow": "none"
          },
          "&:active": {
            "backgroundColor": "var(--theme-base-feedback-success-dark, rgba(27,94,32,1))",
            "boxShadow": "none"
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))",
            "backgroundColor": "var(--theme-base-action-disabled-background, rgba(0,0,0,0.12))",
            "boxShadow": "none"
          }
        },
        "outlinedSuccess": {
          "color": "var(--theme-base-feedback-success-main, rgba(46,125,50,1))",
          "borderColor": "var(--theme-base-feedback-success-main, rgba(46,125,50,1))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-secondary-states-hover, rgba(65,94,91,0.06))"
          }
        },
        "textSuccess": {
          "color": "var(--theme-base-feedback-success-main, rgba(46,125,50,1))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-secondary-states-hover, rgba(65,94,91,0.06))"
          }
        }
      }
    },
    "MuiCard": {
      "defaultProps": {
        "elevation": 0
      },
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "border": "1px solid var(--theme-base-divider, rgba(0,0,0,0.11999999731779099))"
        }
      },
      "variants": [
        {
          "props": {
            "elevation": 0
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-0, var(--theme-base-surface-level-0, rgba(158,158,158,1)))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-0, var(--theme-base-surface-level-0, rgba(158,158,158,1)))"
          }
        },
        {
          "props": {
            "elevation": 1
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-1, var(--theme-base-surface-level-1, rgba(189,189,189,1)))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-1, var(--theme-base-surface-level-1, rgba(189,189,189,1)))"
          }
        },
        {
          "props": {
            "elevation": 2
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-2, var(--theme-base-surface-level-2, rgba(210,210,210,1)))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-2, var(--theme-base-surface-level-2, rgba(210,210,210,1)))"
          }
        },
        {
          "props": {
            "elevation": 3
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-3, var(--theme-base-surface-level-3, rgba(224,224,224,1)))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-3, var(--theme-base-surface-level-3, rgba(224,224,224,1)))"
          }
        },
        {
          "props": {
            "elevation": 4
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-4, var(--theme-base-surface-level-4, rgba(238,238,238,1)))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-4, var(--theme-base-surface-level-4, rgba(238,238,238,1)))"
          }
        },
        {
          "props": {
            "elevation": 5
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-5, var(--theme-base-surface-level-5, rgba(245,245,245,1)))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-5, var(--theme-base-surface-level-5, rgba(245,245,245,1)))"
          }
        },
        {
          "props": {
            "elevation": 6
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-6, var(--theme-base-surface-level-6, rgba(255,255,255,1)))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-6, var(--theme-base-surface-level-6, rgba(255,255,255,1)))"
          }
        }
      ]
    },
    "MuiChip": {
      "styleOverrides": {
        "root": {
          "borderRadius": 100,
          "border": "1px solid var(--theme-base-divider, rgba(0,0,0,0.11999999731779099))",
          "backgroundColor": "var(--theme-base-surface-raised, rgba(255,255,255,1))",
          "color": "var(--theme-base-text-secondary, rgba(0,0,0,0.699999988079071))",
          "& .MuiChip-deleteIcon": {
            "opacity": 0.5
          }
        },
        "filled": {},
        "outlined": {},
        "colorPrimary": {},
        "colorSecondary": {},
        "colorError": {},
        "colorWarning": {},
        "colorInfo": {},
        "colorSuccess": {}
      },
      "variants": [
        {
          "props": {
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "var(--theme-base-surface-raised, rgba(255,255,255,1))",
            "color": "var(--theme-base-text-secondary, rgba(0,0,0,0.699999988079071))",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-text-secondary, rgba(0,0,0,0.699999988079071))",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "var(--theme-base-divider, rgba(0,0,0,0.11999999731779099))",
            "color": "var(--theme-base-text-secondary, rgba(0,0,0,0.699999988079071))",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-text-secondary, rgba(0,0,0,0.699999988079071))",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "default",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "var(--theme-base-components-chip-default-close-fill, #f5f5f5)",
            "color": "var(--theme-base-text-primary, rgba(0,0,0,0.8700000047683716))",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-text-primary, rgba(0,0,0,0.8700000047683716))",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "default",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "var(--theme-base-components-chip-default-enabled-border, #bdbdbd)",
            "color": "var(--theme-base-text-primary, rgba(0,0,0,0.8700000047683716))",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-text-primary, rgba(0,0,0,0.8700000047683716))",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "primary",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "var(--theme-base-palette-primary-main, #1976d2)",
            "color": "var(--theme-base-palette-primary-contrast-text, #ffffff)",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-primary-contrast-text, #ffffff)",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "primary",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "var(--theme-base-palette-primary-main, #1976d2)",
            "color": "var(--theme-base-palette-primary-main, #1976d2)",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-primary-main, #1976d2)",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "secondary",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "var(--theme-base-palette-secondary-main, #9c27b0)",
            "color": "var(--theme-base-palette-secondary-contrast-text, #ffffff)",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-secondary-contrast-text, #ffffff)",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "secondary",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "var(--theme-base-palette-secondary-main, #9c27b0)",
            "color": "var(--theme-base-palette-secondary-main, #9c27b0)",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-secondary-main, #9c27b0)",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "error",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "var(--theme-base-palette-error-main, #d32f2f)",
            "color": "var(--theme-base-palette-error-contrast-text, #ffffff)",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-error-contrast-text, #ffffff)",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "error",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "var(--theme-base-palette-error-main, #d32f2f)",
            "color": "var(--theme-base-palette-error-main, #d32f2f)",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-error-main, #d32f2f)",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "warning",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "var(--theme-base-palette-warning-main, #ed6c02)",
            "color": "var(--theme-base-palette-warning-contrast-text, var(--theme-base-text-primary, rgba(0,0,0,0.8700000047683716)))",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-warning-contrast-text, var(--theme-base-text-primary, rgba(0,0,0,0.8700000047683716)))",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "warning",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "var(--theme-base-palette-warning-main, #ed6c02)",
            "color": "var(--theme-base-palette-warning-main, #ed6c02)",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-warning-main, #ed6c02)",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "info",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "var(--theme-base-palette-info-main, #0288d1)",
            "color": "var(--theme-base-palette-info-contrast-text, #ffffff)",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-info-contrast-text, #ffffff)",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "info",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "var(--theme-base-palette-info-main, #0288d1)",
            "color": "var(--theme-base-palette-info-main, #0288d1)",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-info-main, #0288d1)",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "success",
            "variant": "filled"
          },
          "style": {
            "backgroundColor": "var(--theme-base-palette-success-main, #2e7d32)",
            "color": "var(--theme-base-palette-success-contrast-text, #ffffff)",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-success-contrast-text, #ffffff)",
              "opacity": 0.5
            }
          }
        },
        {
          "props": {
            "color": "success",
            "variant": "outlined"
          },
          "style": {
            "backgroundColor": "transparent",
            "borderColor": "var(--theme-base-palette-success-main, #2e7d32)",
            "color": "var(--theme-base-palette-success-main, #2e7d32)",
            "& .MuiChip-deleteIcon": {
              "color": "var(--theme-base-palette-success-main, #2e7d32)",
              "opacity": 0.5
            }
          }
        }
      ]
    },
    "MuiFormControl": {
      "styleOverrides": {
        "root": {
          "backgroundColor": "transparent",
          "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))",
          "borderRadius": "4px"
        }
      }
    },
    "MuiFormHelperText": {
      "styleOverrides": {
        "root": {
          "color": "var(--theme-base-text-secondary, rgba(0,0,0,0.6))",
          "backgroundColor": "transparent"
        }
      }
    },
    "MuiFormLabel": {
      "styleOverrides": {
        "root": {
          "color": "var(--theme-base-text-secondary, rgba(0,0,0,0.6))",
          "fontWeight": 500,
          "fontSize": "1rem"
        },
        "asterisk": {
          "color": "var(--theme-base-primary-main, rgba(25,118,210,1))"
        }
      }
    },
    "MuiMenu": {
      "styleOverrides": {
        "paper": {
          "borderRadius": 8,
          "backgroundColor": "var(--theme-base-components-input-outlined-background-fill, rgba(255,255,255,1))",
          "boxShadow": "rgba(210,210,210,1)",
          "minWidth": 160,
          "padding": "4px 0"
        },
        "list": {
          "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))",
          "paddingTop": 8,
          "paddingBottom": 8,
          "paddingLeft": 16,
          "paddingRight": 16
        }
      }
    },
    "MuiMenuItem": {
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "textTransform": "none",
          "color": "var(--theme-base-text-primary, rgba(33,33,33,1))",
          "backgroundColor": "var(--theme-base-components-input-outlined-background-fill, rgba(255,255,255,1))",
          "&:hover": {
            "backgroundColor": "var(--theme-base-action-hover, rgba(0,0,0,0.04))"
          },
          "&.Mui-selected": {
            "backgroundColor": "var(--theme-base-primary-main, rgba(50,98,141,1))",
            "color": "var(--theme-base-on-primary, #fff)",
            "&:hover": {
              "backgroundColor": "var(--theme-base-primary-dark, rgba(33,66,99,1))"
            }
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))",
            "backgroundColor": "var(--theme-base-action-disabled-background, rgba(0,0,0,0.12))"
          },
          "&:focus-visible": {
            "outline": "2px solid var(--theme-base-primary-focus-ring, #1976d2)",
            "outlineOffset": 2
          }
        }
      }
    },
    "MuiPaper": {
      "defaultProps": {
        "elevation": 0
      },
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))"
        },
        "outlined": {
          "border": "1px solid var(--theme-base-divider, rgba(0,0,0,0.12))",
          "backgroundColor": "var(--theme-base-surface, rgba(255,255,255,1))",
          "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))"
        }
      },
      "variants": [
        {
          "props": {
            "elevation": 0
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-0, rgba(158,158,158,1))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-0, rgba(158,158,158,1))",
            "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))"
          }
        },
        {
          "props": {
            "elevation": 1
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-1, rgba(189,189,189,1))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-1, rgba(189,189,189,1))",
            "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))"
          }
        },
        {
          "props": {
            "elevation": 2
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-2, rgba(210,210,210,1))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-2, rgba(210,210,210,1))",
            "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))"
          }
        },
        {
          "props": {
            "elevation": 3
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-3, rgba(224,224,224,1))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-3, rgba(224,224,224,1))",
            "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))"
          }
        },
        {
          "props": {
            "elevation": 4
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-4, rgba(238,238,238,1))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-4, rgba(238,238,238,1))",
            "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))"
          }
        },
        {
          "props": {
            "elevation": 5
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-5, rgba(245,245,245,1))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-5, rgba(245,245,245,1))",
            "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))"
          }
        },
        {
          "props": {
            "elevation": 6
          },
          "style": {
            "backgroundColor": "var(--theme-base-background-elevations-level-6, rgba(255,255,255,1))",
            "--mui-palette-background-paper": "var(--theme-base-background-elevations-level-6, rgba(255,255,255,1))",
            "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))"
          }
        }
      ]
    },
    "MuiRadio": {
      "styleOverrides": {
        "root": {
          "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))",
          "&.Mui-checked": {
            "color": "var(--theme-base-primary-main, rgba(25,118,210,1))"
          },
          "&:hover": {
            "backgroundColor": "var(--theme-base-primary-states-hover, rgba(25,118,210,0.04))"
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))"
          },
          "&:focus-visible": {
            "outline": "2px solid var(--theme-base-primary-focus-ring, #1976d2)",
            "outlineOffset": 2,
            "borderRadius": 8
          }
        }
      }
    },
    "MuiSelect": {
      "styleOverrides": {
        "select": {
          "&:focus": {
            "backgroundColor": "transparent"
          },
          "color": "var(--theme-base-text-primary, rgba(33,33,33,1))",
          "backgroundColor": "var(--theme-base-components-input-outlined-background-fill, rgba(255,255,255,1))",
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))",
            "backgroundColor": "var(--theme-base-action-disabled-background, rgba(0,0,0,0.12))"
          }
        },
        "icon": {
          "color": "var(--theme-base-text-secondary, rgba(0,0,0,0.54))"
        }
      }
    },
    "MuiSnackbar": {
      "styleOverrides": {
        "root": {
          "& .MuiPaper-root, & .MuiSnackbarContent-root": {
            "borderRadius": 8
          },
          "& .MuiSnackbarContent-root": {
            "backgroundColor": "var(--theme-base-feedback-info-main, #0288d1)",
            "color": "var(--theme-base-feedback-info-contrast-text, #ffffff)"
          },
          "& .MuiAlert-filledSuccess": {
            "backgroundColor": "var(--theme-base-feedback-success-main, #2e7d32)",
            "color": "var(--theme-base-feedback-success-contrast-text, #ffffff)"
          },
          "& .MuiAlert-filledInfo": {
            "backgroundColor": "var(--theme-base-feedback-info-main, #0288d1)",
            "color": "var(--theme-base-feedback-info-contrast-text, #ffffff)"
          },
          "& .MuiAlert-filledWarning": {
            "backgroundColor": "var(--theme-base-feedback-warning-main, #ed6c02)",
            "color": "var(--theme-base-feedback-warning-contrast-text, #1a1300)"
          },
          "& .MuiAlert-filledError": {
            "backgroundColor": "var(--theme-base-feedback-error-main, #d32f2f)",
            "color": "var(--theme-base-feedback-error-contrast-text, #ffffff)"
          },
          "& .MuiAlert-standardSuccess": {
            "backgroundColor": "var(--theme-base-feedback-success-light, #e8f5e9)",
            "color": "var(--theme-base-feedback-success-dark, #1b5e20)"
          },
          "& .MuiAlert-standardInfo": {
            "backgroundColor": "var(--theme-base-feedback-info-light, #e3f2fd)",
            "color": "var(--theme-base-feedback-info-dark, #01579b)"
          },
          "& .MuiAlert-standardWarning": {
            "backgroundColor": "var(--theme-base-feedback-warning-light, #fff4e5)",
            "color": "var(--theme-base-feedback-warning-dark, #b53d00)"
          },
          "& .MuiAlert-standardError": {
            "backgroundColor": "var(--theme-base-feedback-error-light, #fde7e9)",
            "color": "var(--theme-base-feedback-error-dark, #9a0007)"
          },
          "& .MuiAlert-outlinedSuccess": {
            "color": "var(--theme-base-feedback-success-dark, #1b5e20)",
            "border": "1px solid",
            "borderColor": "var(--theme-base-feedback-success-main, #2e7d32)"
          },
          "& .MuiAlert-outlinedInfo": {
            "color": "var(--theme-base-feedback-info-dark, #01579b)",
            "border": "1px solid",
            "borderColor": "var(--theme-base-feedback-info-main, #0288d1)"
          },
          "& .MuiAlert-outlinedWarning": {
            "color": "var(--theme-base-feedback-warning-dark, #b53d00)",
            "border": "1px solid",
            "borderColor": "var(--theme-base-feedback-warning-main, #ed6c02)"
          },
          "& .MuiAlert-outlinedError": {
            "color": "var(--theme-base-feedback-error-dark, #9a0007)",
            "border": "1px solid",
            "borderColor": "var(--theme-base-feedback-error-main, #d32f2f)"
          }
        }
      }
    },
    "MuiSwitch": {
      "styleOverrides": {
        "switchBase": {
          "&.MuiSwitch-colorPrimary.Mui-checked": {
            "color": "var(--theme-base-palette-primary-main, #1976d2)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "color-mix(in srgb, var(--theme-base-palette-primary-main, #1976d2) 50%, transparent)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "var(--theme-base-palette-primary-main, #1976d2)"
            }
          },
          "&.MuiSwitch-colorSecondary.Mui-checked": {
            "color": "var(--theme-base-palette-secondary-main, #9c27b0)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "color-mix(in srgb, var(--theme-base-palette-secondary-main, #9c27b0) 50%, transparent)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "var(--theme-base-palette-secondary-main, #9c27b0)"
            }
          },
          "&.MuiSwitch-colorError.Mui-checked": {
            "color": "var(--theme-base-palette-error-main, #d32f2f)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "color-mix(in srgb, var(--theme-base-palette-error-main, #d32f2f) 50%, transparent)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "var(--theme-base-palette-error-main, #d32f2f)"
            }
          },
          "&.MuiSwitch-colorWarning.Mui-checked": {
            "color": "var(--theme-base-palette-warning-main, #ffa726)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "color-mix(in srgb, var(--theme-base-palette-warning-main, #ffa726) 50%, transparent)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "var(--theme-base-palette-warning-main, #ffa726)"
            }
          },
          "&.MuiSwitch-colorInfo.Mui-checked": {
            "color": "var(--theme-base-palette-info-main, #0288d1)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "color-mix(in srgb, var(--theme-base-palette-info-main, #0288d1) 50%, transparent)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "var(--theme-base-palette-info-main, #0288d1)"
            }
          },
          "&.MuiSwitch-colorSuccess.Mui-checked": {
            "color": "var(--theme-base-palette-success-main, #388e3c)",
            "& + .MuiSwitch-track": {
              "backgroundColor": "color-mix(in srgb, var(--theme-base-palette-success-main, #388e3c) 50%, transparent)"
            },
            "& .MuiSwitch-thumb": {
              "backgroundColor": "var(--theme-base-palette-success-main, #388e3c)"
            }
          },
          "&.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))"
          },
          "&.Mui-checked.Mui-disabled": {
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.38))",
            "& + .MuiSwitch-track": {
              "opacity": 0.5
            }
          }
        },
        "thumb": {
          "backgroundColor": "var(--theme-base-input-white-bg, #fff)"
        },
        "track": {
          "backgroundColor": "var(--theme-base-action-disabled-bg, rgba(0,0,0,0.12))"
        }
      }
    },
    "MuiTab": {
      "styleOverrides": {
        "root": {
          "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))",
          "&.Mui-selected": {
            "color": "var(--theme-base-primary-main, rgba(25,118,210,1))"
          },
          "&:hover": {
            "backgroundColor": "var(--theme-base-primary-states-hover, rgba(25,118,210,0.04))"
          },
          "&:focus-visible": {
            "outline": "2px solid var(--theme-base-primary-focus-ring, #1976d2)",
            "outlineOffset": 2,
            "borderRadius": 0
          }
        }
      }
    },
    "MuiTabs": {
      "styleOverrides": {
        "root": {
          "backgroundColor": "transparent",
          "minHeight": 48,
          "borderBottom": "1px solid var(--theme-base-divider, rgba(0,0,0,0.12))"
        },
        "indicator": {
          "height": 3,
          "borderRadius": 2,
          "backgroundColor": "var(--theme-base-primary-main, #1976d2)"
        },
        "scrollButtons": {
          "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))",
          "&.Mui-disabled": {
            "opacity": 0.3
          }
        },
        "flexContainer": {
          "minHeight": 48
        }
      }
    },
    "MuiTextField": {
      "defaultProps": {
        "variant": "outlined"
      },
      "styleOverrides": {
        "root": {
          "borderRadius": 8
        }
      }
    },
    "MuiOutlinedInput": {
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "backgroundColor": "var(--theme-base-components-input-outlined-background-fill, var(--theme-base-background-elevations-level-0, rgba(158,158,158,1)))",
          "--mui-palette-background-paper": "var(--theme-base-components-input-outlined-background-fill, var(--theme-base-background-elevations-level-0, rgba(158,158,158,1)))",
          "&.Mui-disabled": {
            "backgroundColor": "var(--theme-base-action-disabled-background, rgba(0,0,0,0.11999999731779099))",
            "color": "var(--theme-base-action-disabled, rgba(0,0,0,0.3799999952316284))"
          },
          "&.Mui-focused": {
            "boxShadow": "0 0 0 1px var(--theme-base-primary-states-focus, rgba(25,118,210,0.12))"
          },
          "&:hover .MuiOutlinedInput-notchedOutline": {
            "borderColor": "var(--theme-base-divider, rgba(0,0,0,0.11999999731779099))"
          },
          "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
            "borderColor": "var(--theme-base-primary-main, rgba(50,98,141,1))"
          },
          "&.Mui-error .MuiOutlinedInput-notchedOutline": {
            "borderColor": "var(--theme-base-feedback-error-main, rgba(211,47,47,1))"
          },
          "&.Mui-focused.MuiInputBase-colorWarning .MuiOutlinedInput-notchedOutline": {
            "borderColor": "var(--theme-base-feedback-warning-main, rgba(237,108,2,1))"
          },
          "&.Mui-focused.MuiInputBase-colorInfo .MuiOutlinedInput-notchedOutline": {
            "borderColor": "var(--theme-base-feedback-info-main, rgba(2,136,209,1))"
          },
          "&.Mui-focused.MuiInputBase-colorSuccess .MuiOutlinedInput-notchedOutline": {
            "borderColor": "var(--theme-base-feedback-success-main, rgba(46,125,50,1))"
          }
        },
        "notchedOutline": {
          "borderColor": "var(--theme-base-divider, rgba(0,0,0,0.11999999731779099))"
        },
        "input": {
          "color": "var(--theme-base-text-primary, rgba(0,0,0,0.87))"
        },
        "adornedStart": {},
        "adornedEnd": {},
        "colorPrimary": {},
        "colorSecondary": {}
      }
    },
    "MuiTypography": {
      "defaultProps": {},
      "styleOverrides": {
        "root": {
          "borderRadius": 8,
          "color": "var(--theme-base-text-primary, rgba(0,0,0,0.8700000047683716))"
        },
        "colorPrimary": {
          "color": "var(--theme-base-primary-main, rgba(50,98,141,1))"
        },
        "colorSecondary": {
          "color": "var(--theme-base-secondary-main, rgba(65,94,91,1))"
        },
        "colorTextPrimary": {
          "color": "var(--theme-base-text-primary, rgba(0,0,0,0.8700000047683716))"
        },
        "colorTextSecondary": {
          "color": "var(--theme-base-text-secondary, rgba(0,0,0,0.699999988079071))"
        },
        "colorError": {
          "color": "var(--theme-base-feedback-error-main, rgba(211,47,47,1))"
        },
        "colorWarning": {
          "color": "var(--theme-base-feedback-warning-main, rgba(237,108,2,1))"
        },
        "colorInfo": {
          "color": "var(--theme-base-feedback-info-main, rgba(2,136,209,1))"
        },
        "colorSuccess": {
          "color": "var(--theme-base-feedback-success-main, rgba(46,125,50,1))"
        }
      }
    }
  }
};
const theme = createTheme(themeOptions);
export default theme;
